import '@material/web/checkbox/checkbox'
import '@material/web/elevation/elevation'
import '@material/web/iconbutton/icon-button'
import '@material/web/switch/switch'
import './components/icons/reset-icon'
import './components/icons/swap-icon'
import './components/select'
import './index.css'
